FROM python:3.12-slim

# Instala dependencias del sistema y Node.js
RUN apt-get update \
    && apt-get install -y curl ca-certificates build-essential gnupg --no-install-recommends \
    && curl -fsSL https://deb.nodesource.com/setup_18.x | bash - \
    && apt-get install -y nodejs --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copia package.json del frontend para instalar dependencias de frontend primero (cache layer)
COPY frontend/package*.json frontend/
# Try `npm ci` (fast, uses lockfile). If it fails (e.g. CI lockfile mismatch or peer dep errors),
# fall back to `npm install` with `--legacy-peer-deps` to avoid build failure on Railway.
RUN cd frontend \
    && npm ci --silent || npm install --silent --legacy-peer-deps --no-audit --progress=false --unsafe-perm

# Copia requirements y instala dependencias Python
COPY backend/requirements.txt backend/
RUN pip install --no-cache-dir -r backend/requirements.txt

# Copia todo el proyecto
COPY . .

# Construye el frontend con PUBLIC_URL=/static y mueve el build al backend/static
# además, si el build tiene un `img` a nivel superior (copiado desde `public/img`),
# muévelo dentro de `static/img` para que el mount `/static` entregue /static/img/...
RUN cd frontend \
    && npm run build --silent \
    && rm -rf ../backend/app/static || true \
        && mv build ../backend/app/static \
        && if [ -d ../backend/app/static/img ]; then mkdir -p ../backend/app/static/static/img && mv ../backend/app/static/img/* ../backend/app/static/static/img/ || true; fi \
        # Fix possible double /static/static paths generated by older builds or PUBLIC_URL usage
        && if [ -f ../backend/app/static/index.html ]; then \
                 sed -i "s|/static/static/js/|/static/js/|g" ../backend/app/static/index.html && \
                 sed -i "s|/static/static/css/|/static/css/|g" ../backend/app/static/index.html && \
                 sed -i "s|/static/static/media/|/static/media/|g" ../backend/app/static/index.html || true; \
             fi

# Copia entrypoint
COPY scripts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8080

# Entrypoint usa la variable de entorno PORT puesta por Railway. Por defecto 8000.
CMD ["/entrypoint.sh"]